# 文档 https://docs.litellm.ai/docs/proxy/docker_quick_start#pre-requisites

# run
run:
	# api: http://127.0.0.1:4000/
	# ui: http://127.0.0.1:4000/ui/  默认用户名密码 admin MASTER_KEY环境变量值
	docker compose up -d
