# web: http://127.0.0.1:8070/
# 默认用户名: apollo
# 密码：admin

amd:
	docker-compose up -d

# 如果使用的是 arm 架构的机器，例如 mac m1
arm_up:
	docker-compose -f docker-compose-arm64.yml up -d
arm_stop:
	docker-compose -f docker-compose-arm64.yml stop
arm_start:
	docker-compose -f docker-compose-arm64.yml start
arm_down:
	docker-compose -f docker-compose-arm64.yml down
