
## run
run:
	# web browser: http://127.0.0.1:3001
	# github地址: https://github.com/tbphp/gpt-load
	docker run -d --name gpt-load \
    -p 3001:3001 \
    -e AUTH_KEY=oTy9M7hUD5ndn4 \
    -v ./data:/app/data \
    ghcr.io/tbphp/gpt-load:latest
